touchscreen: fts_spi: Add missing type specifier in fts_update_touchmode_data
Fixes following error:
../drivers/input/touchscreen/fts_spi/fts.c:6162:9: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 6162 |         static expert_mode = false;
      |         ~~~~~~ ^
      |         int

Change-Id: I34c51023bd66604cfd8f0203f4c37269401808f9
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>